rule_files:
  - pybal.yaml
evaluation_interval: 1m
tests:
  - interval: 1m
    external_labels:
      site: eqiad
    input_series:
      # Should trigger a fail
      - series: 'pybal_bgp_session_established{cluster="lvs", instance="lvs1234:9090", job="pybal", local_asn="64600", peer="192.0.2.1"}'
        values: '1 0 0 0 0 0 0'
      - series: 'pybal_bgp_enabled{cluster="lvs", instance="lvs1234:9090", job="pybal"}'
        values: '1 1 1 1 1 1 1'
      # Should pass
      - series: 'pybal_bgp_session_established{cluster="lvs", instance="lvs5678:9090", job="pybal", local_asn="64600", peer="192.0.2.2"}'
        values: '1 1 1 1 1 1 1'
      - series: 'pybal_bgp_enabled{cluster="lvs", instance="lvs5678:9090", job="pybal"}'
        values: '1 1 1 1 1 1 1'
    alert_rule_test:
      - alertname: PyBalBGPUnstable
        eval_time: 6m
        exp_alerts:
          - exp_labels:
              cluster: "lvs"
              job: "pybal"
              instance: "lvs1234:9090"
              local_asn: "64600"
              peer: "192.0.2.1"
              severity: warning
              team: traffic
            exp_annotations:
              summary: "PyBal BGP sessions on instance lvs1234 are failing"
              description: "PyBal BGP session establishment with the peer 192.0.2.1 is unstable on host lvs1234."
              dashboard: "https://grafana.wikimedia.org/d/000000488/pybal-bgp?var-datasource=eqiad%20prometheus/ops&var-server=lvs1234"
              runbook: 'https://wikitech.wikimedia.org/wiki/PyBal#Alerts'
